on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v2

        uses: actions/setup-node@v2
        with:
          node-version: '12'

        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

        run: npm install

        run: node index.js

        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'